# Generated by Django 3.0.8 on 2021-09-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(max_length=400, verbose_name='Request Headers')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Datetime of the visit')),
                ('tracker_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Link', verbose_name='Tracker link for this visit')),
            ],
        ),
    ]
