# Generated by Django 3.0.8 on 2021-09-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='tracker_link',
            new_name='link',
        ),
    ]
