# Generated by Django 3.0.8 on 2021-09-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(max_length=100, verbose_name='Tracker link')),
                ('is_enabled', models.BooleanField(verbose_name='Is the link enable?')),
                ('visit_count', models.PositiveIntegerField(verbose_name='Total visit count for this link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime at the creation time')),
                ('last_opened', models.DateTimeField(verbose_name='Datetime at last opened')),
                ('notifications_enabled', models.BooleanField(verbose_name='Are notifications enabled for this link?')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator of this link')),
            ],
        ),
    ]
