# Generated by Django 3.0.8 on 2021-09-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20210912_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_opened',
            field=models.DateTimeField(null=True, verbose_name='Datetime at last opened'),
        ),
    ]
