# Generated by Django 3.0.8 on 2021-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20210912_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Tracker link uuid'),
        ),
    ]
