# Generated by Django 3.0.8 on 2021-09-12 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210912_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime at last opened'),
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e1cb9632-6ca6-412a-b5d9-2e428e32e1b1'), max_length=100, primary_key=True, serialize=False, verbose_name='Tracker link uuid'),
        ),
    ]
