# Generated by Django 3.0.8 on 2021-09-12 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20210912_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='vivek', max_length=50, unique=True, verbose_name='Tracker Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a2fb1748-3667-444c-ac36-233f59b81da5'), max_length=100, primary_key=True, serialize=False, verbose_name='Tracker link uuid'),
        ),
    ]
