# Generated by Django 3.0.8 on 2021-09-12 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20210912_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cd8ea478-c0a2-4a8f-9e61-6d7aae7dec33'), max_length=100, primary_key=True, serialize=False, verbose_name='Tracker link uuid'),
        ),
    ]
