# Generated by Django 3.0.8 on 2021-09-12 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20210912_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ca620856-3a60-4959-84c3-4a9ebc92114b'), max_length=100, primary_key=True, serialize=False, verbose_name='Tracker link uuid'),
        ),
    ]
