# Generated by Django 3.0.8 on 2021-09-12 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_auto_20210912_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='first_opened',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime of first opened'),
        ),
        migrations.AlterField(
            model_name='link',
            name='creator',
            field=models.CharField(default=0, max_length=100, verbose_name='Creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d470a17d-1707-4d99-962e-26107a342cc2'), max_length=100, primary_key=True, serialize=False, verbose_name='Tracker link uuid'),
        ),
    ]
